#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Indirect Trace Generated By Pin
import pymongoloader
# Symbol path: .;C:\downstreamstore
# Looking for routine 
# CheckHeap            0x1
# CheckStack           0x1
# CheckSymbols         0x1
# CheckText            0
# CheckWhitelistSymbols0
# InstrumentIndirect   0x1
# InstrumentMov        0x1
time_begin=[2013,10,29,14,36,57]
now      ='-'.join([str(i) for i in time_begin])
dbName   = 'IdaSplode-readercrash-py-' + now
if __name__ == '__main__':
  pymongoloader.ProcessFileIntoCollectition(__file__ + '.modules.py', dbName, 'modules')
  pymongoloader.ProcessFileIntoCollectition(__file__ + '.traces.py', dbName, 'traces')

# Whitelisting C:\Program Files\Adobe\Reader 11.0\Reader\rt3d.dll based on rt3d
time_end=[2013,10,29,14,40,57]
# Time Elapsed: 0 hours, 3 minutes, 59 seconds
# eof
