#!/usr/bin/env python
# -*- coding: latin-1 -*-
"""
IdaSplode settings
"""

#
# Default color for instructions.
# Format: 0xRRGGBB
#
COLOR_INS_RESET     = 0xffffff

#
# Color to set an instruction if it was executed during the run.
# Format: 0xRRGGBB
#
COLOR_INS_EXECUTED  = 0xeeeeee

#
# Color to set an instruction if it was executed during the run
# AND we have extra metadata for it.
# Format: 0xRRGGBB
#
COLOR_INS_ENHANCED  = 0xcccccc

#
# Color to set data if it was READ or WRITTEN during the trace
#
COLOR_DATA_REFERENCE = 0xccffcc

#
# Color to set an instruction if it was only executed during Trace A
# during trace comparison.
# Format: 0xRRGGBB
#
COLOR_INS_TRACE_A_ONLY   = 0xffcccc

#
# Same as COLOR_INS_TRACE_A_ONLY, but for trace B.
# Format: 0xRRGGBB
#
COLOR_INS_TRACE_B_ONLY   = 0xccccff

#
# Color to set an instruction if it was executed by BOTH traces
# Format: 0xRRGGBB
#
COLOR_INS_TRACE_BOTH     = 0xeeeeee

#
# Dynamic section in which to create function stubs for dynamically
# resolved routines.
#
SECTION_NAME_DYNAMIC = '.idasplode'

#
# Set to True if the most-recently-used database should be automatically
# loaded with IdaSplode is loaded
#
DATABASE_AUTO_LOAD_MOST_RECENT = True

#
# Autogenerated field name prefix
#
RECONSTRUCTED_FIELD_NAME_PREFIX = "autofield_"

#
# Number of stack traces necessary to match for auto-analysis
#
RECONSTRUCTED_STACK_TRACE_FRAMES = 3

#
# Banned API functions for structure reconstruction
#
RECONSTRUCTED_BANNED_API_CHUNKS = ['memcpy','memset','strcpy','strncpy','StringCch','StringCb','strcat','strncat']